#redis:
#  timeout: 6000ms
#  password: '123456'
#  cluster:
#    max-redirects: 3  # 获取失败 最大重定向次数
#    nodes:
#    - 127.0.0.1:7001
#    - 127.0.0.1:7002
#    - 127.0.0.1:7003
#    - 127.0.0.1:7004
#    - 127.0.0.1:7005
#    - 127.0.0.1:7006
#    - 127.0.0.1:7007
#    - 127.0.0.1:7008
#    - 127.0.0.1:7009
#
#  lettuce:
#    pool:
#      max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
#      max-idle: 10 # 连接池中的最大空闲连接
#      min-idle: 5 # 连接池中的最小空闲连接
#      max-wait: -1ms # a连接池最大阻塞等待时间（使用负值表示没有限制）